## Copy


In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3])
x = arr.copy()
arr[0] = 10
print(arr)
print(x)

[10  2  3]
[1 2 3]


## View

In [5]:
arr = np.array([1,2,3])
x = arr.view()
arr[0] = 10
print(arr)
print(x)

[10  2  3]
[10  2  3]


### Check if Array Owns its Data

In [7]:
#  Every NumPy array has the attribute base that returns None if the array owns the data.
#  Otherwise, the base  attribute refers to the original object.

arr = np.array([1,2,3])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3]
