# Filtering Arrays
###  Getting some elements out of an existing array and creating a new array out of them is called filtering.
###  In NumPy, you filter an array using a boolean index list.

### If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [1]:
import numpy as np

#  Create an array from the elements on index 0 and 2:

arr = np.array([1,2,3,4])
x = arr[[True, False, True, False]]
print(x)

[1 3]


### Creating the Filter Array

In [2]:
#  Create a filter array that will return only values higher than 40:

arr = np.array([38,39,40,41,42,43,44])

# Initialize an empty list to store the filter (boolean) values
filter_arr = []

# Loop through each element in the array
for element in arr:
    if element > 40:
        filter_arr.append(True)
# append() is used to store/save the value (True or False) in a list (filter_arr) for later use.
# If you use print(), it will just display on the console, but nothing gets stored — so you can't use it later to filter the array.

    else:
        filter_arr.append(False)

# Apply the boolean filter to the original array to get values > 40
newarr = arr[filter_arr]

# Print the boolean filter array
print(filter_arr)  

# Print the filtered array (values greater than 40)
print(newarr)


[False, False, False, True, True, True, True]
[41 42 43 44]


In [3]:
#   Create a filter array that will return only even elements from the original array:

arr = np.array([1,2,3,4,5,6,7,8,9,10])
filter_arr = []
for x in arr :
    if x % 2 == 0:
        filter_arr.append(True)
    else :
        filter_arr.append(False)

newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


###  Creating Filter Directly From Array

In [5]:
#  Create a filter array that will return only values higher than 40:

arr = np.array([38,39,40,41,42,43,44])
filter_arr = arr > 40
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False False  True  True  True  True]
[41 42 43 44]


In [7]:
#   Create a filter array that will return only even elements from the original array:

arr = np.array([1,2,3,4,5,6,7,8,9,10])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]
