# Iterating Arrays
### Iterating means going through elements one by one.

In [ ]:
import numpy as np

#  Iterating 1-D Arrays
arr = ([1,2,3])
for x in arr :
 print(x)

1
2
3


In [4]:
#  Iterating 2-D Arrays

arr = np.array([[1,2,3,], [4,5,6]])
for x in arr :
    print(x)

[1 2 3]
[4 5 6]


In [5]:
#  Iterate on each scalar element of the 2-D array:

arr = np.array([[1,2,3], [4,5,6]])
for x in arr :
    for y in x :
        print(y)

1
2
3
4
5
6


## Iterating 3-D Arrays
### In a 3-D array it will go through all the 2-D arrays.

In [13]:
#  Iterate on the elements of the following 3-D array:

arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
for x in arr :
 print("x represents the 2D array")
 print(x)

x represents the 2D array
[[1 2 3]
 [4 5 6]]
x represents the 2D array
[[ 7  8  9]
 [10 11 12]]


In [17]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
for x in arr :
    for y in x :
        for z in y :
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12
